LPI-FT                                           OR   LPI-PUMPS TANK LPI-VALVES
LPI-PUMPS                                        OR   LPI-PUMPS-INDEP LPI-PUMPS-CCF
LPI-PUMPS-INDEP                                  AND  LPI-PUMP-A LPI-PUMP-B
LPI-VALVES                                       OR   LPI-VALVES-CCF LPI-VALVES-INDEP
LPI-VALVES-INDEP                                 AND  LPI-VALVE-A LPI-VALVE-B LPI-VALVE-C